# version: "3.9" (supposedly optional)

services:
# first start db
# then start server
# indicate that server depends on db
# i guess you create/specify volumes here too?
  mongo:
    # container_name: sdcdb
    # build: should I used a Dockerfile?
    # image: mongo

    # definitely going to need a Dockerfile for the MongoDB configuration
    build: ./db/

    image: jimmyko360/sdcmongo:1.0

    ports:
      - "27018:27017"
    volumes:
      - sdc:/data/db
      # named volume config goes here

  ratingsreviewsapi:
    container_name: ratingsreviewsapi
    build: .
    # or do I need to refer to the Dockerfile in the server folder?

    image: jimmyko360/ratingsreviewsapi:1.0

    ports:
      - "3000:3000"
      #- "80:3000"
      #I believe this needs to connect 80 to 3000 if I want to deploy on an EC2
    depends_on:
      - "mongo"
    links:
      - "mongo"
      # not sure what this does, this was in Trent's docker-compose file

volumes:
  sdc:
  # named volume config goes here too 
  # I've seen sdc, sdc:, and sdc:{}, not sure which one is correct