version: '3.8'

services:
  nodejs:
    build:
      context: .
    image: orenjiku/sdc_server
    depends_on:
      - mysql
    container_name: sdc_server
    env_file:
      - ./env/.env
    ports:
      - '9000:8080'

  mysql:
    image: mysql:latest
    container_name: sdc_mysql
    env_file: ./env/.env
    volumes:
      - 'sdc-mysql-data:/var/lib/mysql'
    ports:
      - '9001:3306'

volumes:
  sdc-mysql-data: