version: '3.8'

services:
  nodejs:
    build:
      context: .
    image: orenjiku/sdc_server
    depends_on:
      - mysql
    container_name: sdc_server
    restart: unless-stopped
    env_file: ./env/.env
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - 9000:8080
    working_dir: /app
    command: ''

  mysql:
    image: mysql:latest
    container_name: sdc_mysql
    restart: unless-stopped
    env_file: ./env/.env
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    port: 3306:3306